export const ProductsTest = [
	{
		id: 1,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
            productName: "Duke 350",
            qrcode: "Duke 350",
            price: "100 Euro",
            itemsLeft: "10",
			statusId: 1,
			approvalId: 1,
	},
	{
		id: 2,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
            productName: "Kaavalam Jettikal",
            qrcode: "Duke 350",
            price: "10 Euro",
            itemsLeft: "4",
			statusId: 2,
			approvalId: 3,
	},
	{
		id: 3,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
            productName: "Asameese konandras thailam",
            qrcode: "Duke 350",
            price: "150 Euro",
            itemsLeft: "20",
			statusId: 3,
			approvalId: 1,
	},
	{
		id: 4,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
            productName: "Sonu",
            qrcode: "Duke 350",
            price: "200 Euro",
            itemsLeft: "1",
			statusId: 4,
			approvalId: 2,
	},
	// Add more comments as needed
];
