export const ProductsUsers = [
	{
		id: 1,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "ASK",
        firstname: "Akshay",
        lastname: "Sunilkumar",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Paderborn",
	},
	{
		id: 2,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "Baby",
        firstname: "Moiz",
        lastname: "Ladakkutaaa",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Koblenz",
	},
	{
		id: 3,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "Kundan",
        firstname: "Sonu",
        lastname: "Sadanandan",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Frankfurt",
	},
	{
		id: 4,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "Shaji",
        firstname: "Shaji",
        lastname: "Denio",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Hamburg",
	},
	{
		id: 5,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "AJ",
        firstname: "Umakanth",
        lastname: "Sing",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Köln",
    },
    {
		id: 6,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "aparnaji",
        firstname: "Aparna",
        lastname: "George",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Dortmund",
    },
    {
		id: 7,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "JJ",
        firstname: "Joseph",
        lastname: "Joseph",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Düsseldorf",
    },
    {
		id: 8,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "KK",
        firstname: "Kiran",
        lastname: "Shashi",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Munich",
    },
    {
		id: 9,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "delbi",
        firstname: "Delbin",
        lastname: "Shaji",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Berlin",
    },
    {
		id: 10,
		avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        username: "NirupA10",
        firstname: "Ranil",
        lastname: "Mathew",
        checkinTime: "6.3.2024, 16:42:16",
        CheckoutTime: "6.3.2024, 16:42:16",
        shopId: 1,
        userId: 1,
        amountPayed: 20,
        itemsBought: 50,
        shopName: "Container Amsterdam",
	},
	// Add more comments as needed
];
